version: '3.9'

services:
  postgres-db:
    image: postgres:15.5
    container_name: postgres-db
    environment:
      POSTGRES_DB: movie-lib-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    profiles: ["test", "release"]
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - movie-lib-data:/var/lib/postgresql/data

volumes:
  movie-lib-data:
