version: '3.9'

services:
  postgres-db:
    image: postgres:15.5
    container_name: postgres-db
    environment:
      POSTGRES_DB: movie-lib-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    profiles: ["test", "release"]
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - movie-lib-data:/var/lib/postgresql/data

  movie-lib:
    build: ./
    command: ./movie-lib-app --docker
    container_name: movie-lib
    profiles: ["release"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  movie-lib-data:
