"postgres-movie-lib":
  "username": "root"
  "password": "root"
  "host": "localhost"
  "port": 5432
  "dbname": "movie-lib-db"
  "sslmode": "disable"

"http-server":
  "host": "localhost"
  "port": 8080
